In [ ]:
from google.colab import files
import pandas as pd

uploaded = files.upload()

Saving geography.csv to geography.csv

In [ ]:
df=pd.read_csv("geography.csv")
df.head()

     zip       city region      district
0  15201  Hai Phong   East  District #13
1  15202     Phu Ly   East  District #13
2  15203   Viet Tri   East  District #13
3  15204  Bac Giang   East  District #13
4  15205  Bac Giang   East  District #13

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39948 entries, 0 to 39947
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   zip       39948 non-null  int64
 1   city      39948 non-null  object
 2   region    39948 non-null  object
 3   district  39948 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.2+ MB

In [ ]:
df.isna().sum()

zip         0
city        0
region      0
district    0
dtype: int64

In [ ]:
display(df['zip'].is_unique)
df['zip'].isna().sum()

True

np.int64(0)

In [ ]:
#display(df[(df['city']=="")| df['city'].isnull()])
df['city'].isnull()

0        False
1        False
2        False
3        False
4        False
         ...
39943    False
39944    False
39945    False
39946    False
39947    False
Name: city, Length: 39948, dtype: bool

In [ ]:
df['region'].isnull()

0        False
1        False
2        False
3        False
4        False
         ...
39943    False
39944    False
39945    False
39946    False
39947    False
Name: region, Length: 39948, dtype: bool

In [ ]:
df['district'].isnull()

0        False
1        False
2        False
3        False
4        False
         ...
39943    False
39944    False
39945    False
39946    False
39947    False
Name: district, Length: 39948, dtype: bool

In [ ]:
print('Trùng zip   :', df.duplicated(subset=['zip']).sum())
print('Trùng bộ ba :', df.duplicated(subset=['city', 'region', 'district']).sum(), '(bình thường)')

# Chuyển cột phân loại sang category
for col in ['city', 'region', 'district']:
    df[col] = df[col].astype('category')

Trùng zip   : 0
Trùng bộ ba : 39414 (bình thường)

In [ ]:
print('Tổng số dòng     :', len(df))
print('Tổng số zip trùng:', df.duplicated(subset=['zip']).sum())
print('Tổng số null     :', df.isna().sum().sum())

Tổng số dòng     : 39948
Tổng số zip trùng: 0
Tổng số null     : 0

In [ ]:
df.to_csv('geography_cleaned.csv', index=False, encoding='utf-8-sig')