In [1]:
import pandas as pd
import numpy as np

In [2]:
# Đọc file inventory.csv từ thư mục hiện tại
df = pd.read_csv("inventory.csv")

print("5 DÒNG ĐẦU TIÊN FILE INVENTORY")
df.head()

5 DÒNG ĐẦU TIÊN FILE INVENTORY

,snapshot_date,product_id,stock_on_hand,units_received,units_sold,stockout_days,days_of_supply,fill_rate,stockout_flag,overstock_flag,reorder_flag,sell_through_rate,product_name,category,segment,year,month
0,2022-10-31,1,3,1,1,2,90.0,0.9333,1,0,0,0.2500,DragonWear MA-01,Casual,All-weather,2022,10
1,2022-11-30,1,3,1,1,1,90.0,0.9667,1,0,0,0.2500,DragonWear MA-01,Casual,All-weather,2022,11
2,2022-12-31,1,3,1,1,1,90.0,0.9667,1,0,0,0.2500,DragonWear MA-01,Casual,All-weather,2022,12
3,2016-04-30,3,35,13,11,2,95.5,0.9333,1,1,0,0.2391,DragonWear MA-03,Casual,All-weather,2016,4
4,2016-05-31,3,36,11,10,1,108.0,0.9667,1,1,0,0.2174,DragonWear MA-03,Casual,All-weather,2016,5

In [3]:
# Kiểm tra kiểu dữ liệu & tổng số dòng/cột (xem có cột nào bị thiếu dữ liệu không)
print("THÔNG TIN CÁC CỘT & KIỂU DỮ LIỆU")
df.info()

THÔNG TIN CÁC CỘT & KIỂU DỮ LIỆU
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60247 entries, 0 to 60246
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   snapshot_date      60247 non-null  object
 1   product_id         60247 non-null  int64
 2   stock_on_hand      60247 non-null  int64
 3   units_received     60247 non-null  int64
 4   units_sold         60247 non-null  int64
 5   stockout_days      60247 non-null  int64
 6   days_of_supply     60247 non-null  float64
 7   fill_rate          60247 non-null  float64
 8   stockout_flag      60247 non-null  int64
 9   overstock_flag     60247 non-null  int64
 10  reorder_flag       60247 non-null  int64
 11  sell_through_rate  60247 non-null  float64
 12  product_name       60247 non-null  object
 13  category           60247 non-null  object
 14  segment            60247 non-null  object
 15  year               60247 non-null  int64
 16  month              60247 non-null  int64
dtypes: float64(3), int64(10), object(4)
memory usage: 7.8+ MB

In [4]:
# 4. Thống kê nhanh các chỉ số cơ bản (Min, Max, Trung bình) của các cột dạng số
print("\n THỐNG KÊ MÔ TẢ CÁC CỘT SỐ")
display(df.describe())

 THỐNG KÊ MÔ TẢ CÁC CỘT SỐ

,product_id,stock_on_hand,units_received,units_sold,stockout_days,days_of_supply,fill_rate,stockout_flag,overstock_flag,reorder_flag,sell_through_rate,year,month
count,60247.000000,60247.000000,60247.000000,60247.000000,60247.000000,60247.000000,60247.000000,60247.000000,60247.000000,60247.0,60247.000000,60247.000000,60247.000000
mean,1311.408468,189.298455,18.046807,15.417764,1.160639,912.677576,0.961312,0.673411,0.762561,0.0,0.152275,2017.222799,6.617292
std,673.051769,316.976124,34.080228,28.404379,1.624490,2587.624108,0.054156,0.468969,0.425517,0.0,0.139291,2.972353,3.385629
min,1.000000,3.000000,1.000000,1.000000,0.000000,5.200000,0.066700,0.000000,0.000000,0.0,0.000400,2012.000000,1.000000
25%,760.000000,15.000000,2.000000,2.000000,0.000000,96.000000,0.933300,0.000000,1.000000,0.0,0.042100,2015.000000,4.000000
50%,1223.000000,62.000000,6.000000,6.000000,1.000000,240.000000,0.966700,1.000000,1.000000,0.0,0.111100,2017.000000,7.000000
75%,1942.000000,210.000000,19.000000,16.000000,2.000000,683.100000,1.000000,1.000000,1.000000,0.0,0.238100,2020.000000,10.000000
max,2412.000000,2673.000000,817.000000,670.000000,28.000000,68100.000000,1.000000,1.000000,1.000000,0.0,0.853100,2022.000000,12.000000

In [5]:
print("SỐ LƯỢNG GIÁ TRỊ NULL TRÊN MỖI CỘT:")
print(df.isna().sum())

# Kiểm tra trùng lặp khóa chính liên hợp (snapshot_date, product_id)
pk_cols = ["snapshot_date", "product_id"]
print("\nSố dòng trùng hoàn toàn 100%:", df.duplicated().sum())
print("Số dòng trùng khóa chính (snapshot_date, product_id):", df.duplicated(subset=pk_cols).sum())

SỐ LƯỢNG GIÁ TRỊ NULL TRÊN MỖI CỘT:
snapshot_date        0
product_id           0
stock_on_hand        0
units_received       0
units_sold           0
stockout_days        0
days_of_supply       0
fill_rate            0
stockout_flag        0
overstock_flag       0
reorder_flag         0
sell_through_rate    0
product_name         0
category             0
segment              0
year                 0
month                0
dtype: int64

Số dòng trùng hoàn toàn 100%: 0
Số dòng trùng khóa chính (snapshot_date, product_id): 0

In [6]:
# 1. Kiểm tra giá trị các cột cờ (Flags) - Chỉ được phép chứa 0 hoặc 1
print("Các giá trị thực tế trong stockout_flag :", df["stockout_flag"].unique())
print("Các giá trị thực tế trong overstock_flag:", df["overstock_flag"].unique())
print("Các giá trị thực tế trong reorder_flag  :", df["reorder_flag"].unique())

# 2. Bắt lỗi giá trị âm hoặc bất thường
print("\n--- KIỂM TRA LỖI DỮ LIỆU BẤT THƯỜNG ---")
print("Số dòng có tồn kho (stock_on_hand) < 0  :", (df["stock_on_hand"] < 0).sum())
print("Số dòng có hàng bán (units_sold) < 0     :", (df["units_sold"] < 0).sum())
print("Số dòng có hàng nhập (units_received) < 0 :", (df["units_received"] < 0).sum())

fill_rate_error = ((df["fill_rate"] < 0) | (df["fill_rate"] > 1)).sum()
print("Số dòng có fill_rate nằm ngoài khoảng [0, 1]:", fill_rate_error)

Các giá trị thực tế trong stockout_flag : [1 0]
Các giá trị thực tế trong overstock_flag: [0 1]
Các giá trị thực tế trong reorder_flag  : [0]

--- KIỂM TRA LỖI DỮ LIỆU BẤT THƯỜNG ---
Số dòng có tồn kho (stock_on_hand) < 0  : 0
Số dòng có hàng bán (units_sold) < 0     : 0
Số dòng có hàng nhập (units_received) < 0 : 0
Số dòng có fill_rate nằm ngoài khoảng [0, 1]: 0

In [7]:
# 1. Chuyển snapshot_date sang dạng datetime
df["snapshot_date"] = pd.to_datetime(df["snapshot_date"], errors="coerce")

# 2. ĐỌC BẢNG PRODUCTS VÀ THỰC HIỆN FK CHECK
try:
    df_products = pd.read_csv("products.csv")
    valid_product_ids = set(df_products["product_id"].dropna().unique())
    
    initial_count = len(df)
    df = df[df["product_id"].isin(valid_product_ids)].copy()
    dropped_rows = initial_count - len(df)
    
    print(f"--- KẾT QUẢ FK CHECK (PRODUCT) ---")
    print(f"Tổng số dòng ban đầu : {initial_count}")
    print(f"Số dòng hợp lệ       : {len(df)}")
    print(f"Số dòng bị loại bỏ   : {dropped_rows}")

except FileNotFoundError:
    print("--- CẢNH BÁO: Không tìm thấy file products.csv, giữ nguyên dữ liệu ---")

# 3. Ép kiểu dữ liệu tối ưu bộ nhớ
df["product_id"] = df["product_id"].astype("int32")
df["stock_on_hand"] = df["stock_on_hand"].astype("int32")
df["units_received"] = df["units_received"].astype("int32")
df["units_sold"] = df["units_sold"].astype("int32")
df["stockout_days"] = df["stockout_days"].astype("int8")

for col in ["stockout_flag", "overstock_flag", "reorder_flag"]:
    df[col] = df[col].astype("int8")

# 4. Lọc đúng 12 cột chuẩn 3NF theo Lược đồ 3NF (Loại bỏ product_name, category, segment, year, month)
cols_3nf = [
    "snapshot_date", "product_id", "stock_on_hand", "units_received", 
    "units_sold", "stockout_flag", "fill_rate", "sell_through_rate", 
    "overstock_flag", "reorder_flag", "stockout_days", "days_of_supply"
]
df = df[cols_3nf]

# 5. Sắp xếp dữ liệu theo Khóa chính (snapshot_date, product_id)
df = df.sort_values(["snapshot_date", "product_id"]).reset_index(drop=True)

# 6. Kiểm tra lại thông tin DataFrame chuẩn 3NF
print("\n--- THÔNG TIN DATAFRAME SAU KHI CHUẨN HÓA 3NF & FK CHECK ---")
df.info()

--- KẾT QUẢ FK CHECK (PRODUCT) ---
Tổng số dòng ban đầu : 60247
Số dòng hợp lệ       : 60247
Số dòng bị loại bỏ   : 0

--- THÔNG TIN DATAFRAME SAU KHI CHUẨN HÓA 3NF & FK CHECK ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60247 entries, 0 to 60246
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   snapshot_date      60247 non-null  datetime64[ns]
 1   product_id         60247 non-null  int32
 2   stock_on_hand      60247 non-null  int32
 3   units_received     60247 non-null  int32
 4   units_sold         60247 non-null  int32
 5   stockout_flag      60247 non-null  int8
 6   fill_rate          60247 non-null  float64
 7   sell_through_rate  60247 non-null  float64
 8   overstock_flag     60247 non-null  int8
 9   reorder_flag       60247 non-null  int8
 10  stockout_days      60247 non-null  int8
 11  days_of_supply     60247 non-null  float64
dtypes: datetime64[ns](1), float64(3), int32(4), int8(4)
memory usage: 3.0 MB

In [8]:
# 1. Định nghĩa đường dẫn file xuất trực tiếp
output_path = "Inventory_snapshot.csv"

# 2. Xuất dữ liệu ra file CSV
df.to_csv("Inventory_snapshot.csv", index=False, sep=",", encoding="utf-8-sig")

# 3. In thông báo hoàn tất
print(f"Tổng số dòng    : {len(df)}")
print(f"Tổng số cột     : {len(df.columns)}")
print(f"Đã xuất file thành công chuẩn 3NF tại: {output_path}")

Tổng số dòng    : 60247
Tổng số cột     : 12
Đã xuất file thành công chuẩn 3NF tại: Inventory_snapshot.csv